apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  ports:
  - name: http
    port: 30007
    protocol: TCP
    targetPort: 30007
  selector:
    app: netflix-app
  type: NodePort
